/**
 * Pentapoemario lila — José Andrés Saldarriaga Medina
 *
 * ARCHIVO GENERADO. No editar a mano: lo reescribe
 *     python3 scripts/importar-docx.py
 * a partir de los .docx de origen/. Para cambiar un poema, usa el panel de
 * administración (/panel) o edita el .docx y vuelve a importar.
 *
 * 8 capítulos · 40 poemas
 */

import type { Categoria, Libro } from '../tipos'

export const AUTOR = 'José Andrés Saldarriaga Medina'
export const OBRA = 'Pentapoemario lila'

/** El poemario al que pertenecen estos capítulos. */
export const CATEGORIA_PENTAPOEMARIO: Categoria = {
  id: 'cat-pentapoemario-lila',
  slug: 'pentapoemario-lila',
  nombre: 'Pentapoemario lila',
  descripcion: 'Cinco poemas por capítulo, cinco versos por poema.',
  orden: 0,
  visible: true,
}

export const LIBROS_PENTAPOEMARIO: Libro[] = [
  {
    id: 'cap-1',
    slug: 'capitulo-1',
    volumen: 'Pentapoemario lila',
    titulo: 'Capítulo primero',
    subtitulo: '5 poemas · capítulo I',
    descripcion: 'Cinco versos por poema. Todos los títulos empiezan por la misma letra.',
    categoria: {
      id: 'cat-pentapoemario-lila',
      slug: 'pentapoemario-lila',
      nombre: 'Pentapoemario lila',
      descripcion: 'Cinco poemas por capítulo, cinco versos por poema.',
      orden: 0,
      visible: true,
    },
    orden: 0,
    colorAcento: '#8B5CF6',
    portadaUrl: null,
    anio: 2026,
    publicado: true,
    paginaBase: 1,
    poemas: [
      {
        id: 'cap1-p0',
        slug: 'provocaciones-fuera-de-tiempo',
        titulo: 'Provocaciones fuera de tiempo',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 0,
        publicado: true,
        estrofas: [
          [
            'Se aquietan las horas al atardecer',
            'Sosegados y fructíferos destinos',
            'Desenmadejando energía pura para crear',
            'En ausencia de la cabeza el cuerpo se pierde',
            'Acude al torpe llamado incansable bandido',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap1-p1',
        slug: 'prudencia-ante-ataques-inesperados',
        titulo: 'Prudencia ante ataques inesperados',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 1,
        publicado: true,
        estrofas: [
          [
            'Invocación para localizar urgente cordura',
            'retrocediendo para verla materializarse',
            'en un abrir y cerrar de ojos ante lo brutal',
            'tantas lágrimas y penas se evitaron hoy',
            'sosegando estampida con breve y calma oración',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap1-p2',
        slug: 'pleonasmo-del-deseo',
        titulo: 'Pleonasmo del deseo',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 2,
        publicado: true,
        estrofas: [
          [
            'El encanto o peligrosidad de secretos,',
            'goteando perseverantes en fálica memoria.',
            'abre compuertas de diques imposibles,',
            'desbordándose de manera desmedida placeres',
            'que ni en esta vida ni en la otra veré.',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap1-p3',
        slug: 'presion-desmedida',
        titulo: 'Presión desmedida',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 3,
        publicado: true,
        estrofas: [
          [
            'Esta noche saldré a tu encuentro,',
            'ataviado de premura, expectativas y fiebre.',
            'candor e inocencia, ¿dónde están?',
            '¿por qué ya nada ni nadie se encuentran en su lugar,',
            'cumpliendo sus metas y objetivos este desborde.',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap1-p4',
        slug: 'planteamientos-indebidos',
        titulo: 'Planteamientos indebidos',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 4,
        publicado: true,
        estrofas: [
          [
            'Nada es estático, todo se mueve a un ritmo.',
            'en el monte de venus, melodías y aromas,',
            'en el campo de marte, fortaleza y aplomo.',
            '¿quién tendrá la última palabra?',
            'cuerpo sosegado o ardiente desvarío.',
          ],
        ],
        planchas: [],
        audios: [],
      },
    ],
  },
  {
    id: 'cap-2',
    slug: 'capitulo-2',
    volumen: 'Pentapoemario lila',
    titulo: 'Capítulo segundo',
    subtitulo: '5 poemas · capítulo II',
    descripcion: 'Cinco versos por poema. Todos los títulos empiezan por la misma letra.',
    categoria: {
      id: 'cat-pentapoemario-lila',
      slug: 'pentapoemario-lila',
      nombre: 'Pentapoemario lila',
      descripcion: 'Cinco poemas por capítulo, cinco versos por poema.',
      orden: 0,
      visible: true,
    },
    orden: 1,
    colorAcento: '#8B5CF6',
    portadaUrl: '/portadas/capitulo-2.jpg',
    anio: 2026,
    publicado: true,
    paginaBase: 17,
    poemas: [
      {
        id: 'cap2-p0',
        slug: 'purpura-letania',
        titulo: 'Púrpura letanía',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 0,
        publicado: true,
        estrofas: [
          [
            'Invocación sagrada sin fe no salva ni cura',
            'confinadas aquellas fábulas para dormir',
            'fragante y expectante serpentea el cuerpo',
            'peinándose sobre sedosa cama al amanecer',
            'coreando melódica y reiterada estructura azul',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap2-p1',
        slug: 'postura-visceral-y-profana',
        titulo: 'Postura visceral y profana',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 1,
        publicado: true,
        estrofas: [
          [
            'Enardecidos y sobredimensionados los minutos',
            'sofocan lo construido entre ambas lenguas',
            'arrepentimientos y penas sobre cuerpos caídos',
            'resurgen gozosas y serenas treguas',
            'en habitual entrega de apasionados fluidos',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap2-p2',
        slug: 'perentorias-y-condenadas',
        titulo: 'Perentorias y condenadas',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 2,
        publicado: true,
        estrofas: [
          [
            'A la caza de grotescas aves perentorias',
            'volando en circulo esperan la ruina del caído',
            'en la ruta de apolíneas y soberbias presas',
            'destelleando arriba un incandescente aro solar',
            'tantas voluntades en esa gresca se han perdido',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap2-p3',
        slug: 'pantomima-del-recuerdo',
        titulo: 'Pantomima del recuerdo',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 3,
        publicado: true,
        estrofas: [
          [
            'Contando cuantos dedos quedan aún en las manos',
            'se aventura a glacial encierro infernal',
            'cabellos sedosos y plateados cubriendo desnudez',
            'frente al espejo lo que ha quedado de vil reflejo',
            'imágenes desenfocadas y borrosas del pasado',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap2-p4',
        slug: 'paraiso-solitario-y-nocturno',
        titulo: 'Paraíso solitario y nocturno',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 4,
        publicado: true,
        estrofas: [
          [
            'Video repetitivo y placentero al atardecer',
            'copas rebosantes y llenas de oscuro goce',
            'otras vacías y cristalinas de lo que pudo ser',
            'brebajes y pociones ¿afrodisiacos o mortíferos?',
            'siempre sobre litera lechosa y gratificante',
          ],
        ],
        planchas: [],
        audios: [],
      },
    ],
  },
  {
    id: 'cap-3',
    slug: 'capitulo-3',
    volumen: 'Pentapoemario lila',
    titulo: 'Capítulo tercero',
    subtitulo: '5 poemas · capítulo III',
    descripcion: 'Cinco versos por poema. Todos los títulos empiezan por la misma letra.',
    categoria: {
      id: 'cat-pentapoemario-lila',
      slug: 'pentapoemario-lila',
      nombre: 'Pentapoemario lila',
      descripcion: 'Cinco poemas por capítulo, cinco versos por poema.',
      orden: 0,
      visible: true,
    },
    orden: 2,
    colorAcento: '#8B5CF6',
    portadaUrl: null,
    anio: 2026,
    publicado: true,
    paginaBase: 33,
    poemas: [
      {
        id: 'cap3-p0',
        slug: 'poderoso-despliegue-de-energia',
        titulo: 'Poderoso despliegue de energía',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 0,
        publicado: true,
        estrofas: [
          [
            'Aterriza medusa gigantesca y luminiscente',
            'sobre expansión atemporal tan poderosa',
            'sueños y prodigios diluyéndose en la mente',
            'tentación de corporalidad tersa y voluptuosa',
            'capullo frágil y tierno deja como remanente',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap3-p1',
        slug: 'primavera-de-acuerdos-y-juramentos-pasajeros',
        titulo: 'Primavera de acuerdos y juramentos pasajeros',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 1,
        publicado: true,
        estrofas: [
          [
            'El amor es mas fuerte y fluido que la sangre',
            'centelleaba su energía entre mente y corazón',
            'a nadie le importó hasta el inicio del invierno',
            '¡que maravillosa estación la breve primavera!',
            'esa donde todo se promete sin culpas ni razón',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap3-p2',
        slug: 'proclive-a-transformacion',
        titulo: 'Proclive a transformación',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 2,
        publicado: true,
        estrofas: [
          [
            'Girando los pétalos se van despidiendo de su núcleo',
            'terminan entre pasos precipitados de mil peatones',
            'asoman abejas en la búsqueda de dorado polen',
            'entre rajaduras de sendero asfaltado surge repentina',
            'perfecta y plateada fluctuación vestida de flor',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap3-p3',
        slug: 'preambulo-hacia-lo-celestial',
        titulo: 'Preámbulo hacia lo celestial',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 3,
        publicado: true,
        estrofas: [
          [
            'Inesperado viaje hacia inagotable fuente',
            'ruta de máxima y venerada sabiduría',
            'brinda experiencias y sorpresas lo vivido',
            'a lo largo de una vida de múltiples senderos',
            'sigue su intuición y escoge su camino',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap3-p4',
        slug: 'perfectas-modulaciones',
        titulo: 'Perfectas modulaciones',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 4,
        publicado: true,
        estrofas: [
          [
            'Perfectas modulaciones sobre floral puente',
            'atmósfera cargada de aromas y emociones',
            'tablones de madera crujiendo con cada paso',
            'descalzos y vestidos de resplandeciente blanco',
            'cruzando a vital encuentro de fuente y origen',
          ],
        ],
        planchas: [],
        audios: [],
      },
    ],
  },
  {
    id: 'cap-4',
    slug: 'capitulo-4',
    volumen: 'Pentapoemario lila',
    titulo: 'Capítulo cuarto',
    subtitulo: '5 poemas · capítulo IV',
    descripcion: 'Cinco versos por poema. Todos los títulos empiezan por la misma letra.',
    categoria: {
      id: 'cat-pentapoemario-lila',
      slug: 'pentapoemario-lila',
      nombre: 'Pentapoemario lila',
      descripcion: 'Cinco poemas por capítulo, cinco versos por poema.',
      orden: 0,
      visible: true,
    },
    orden: 3,
    colorAcento: '#8B5CF6',
    portadaUrl: null,
    anio: 2026,
    publicado: true,
    paginaBase: 49,
    poemas: [
      {
        id: 'cap4-p0',
        slug: 'pocima-para-recordar',
        titulo: 'Pócima para recordar',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 0,
        publicado: true,
        estrofas: [
          [
            'Aletea último recuerdo de tramo ajeno',
            'estimulándose con bebida malsana',
            'hoy se le dio valor entre agua y heno',
            'sustentándose con dulce pera y manzana',
            'despidiéndose con sonido de trueno',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap4-p1',
        slug: 'parcela-intermitente-de-su-realidad',
        titulo: 'Parcela intermitente de su realidad',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 1,
        publicado: true,
        estrofas: [
          [
            'Al pestañear de reojo mirando con sigilo',
            'combatientes aguerridos y sudorosos',
            'acondicionando tibia almohada capto al filo',
            'escenas donde se revelan afectuosos',
            'agarrando báculo por esa ruta me encamino',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap4-p2',
        slug: 'prospero-espiritu-de-agradecimiento',
        titulo: 'Prospero espíritu de agradecimiento',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 2,
        publicado: true,
        estrofas: [
          [
            'En los albores de la humanidad florecía beldad',
            'tan bella, tan tierna, tan exótica',
            'vuelve a florecer en la contemporaneidad',
            'tan distinta, poderosa y enigmática',
            'mostrando sutileza de mágica esencia y fragilidad',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap4-p3',
        slug: 'patriarcado-obsoleto',
        titulo: 'Patriarcado obsoleto',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 3,
        publicado: true,
        estrofas: [
          [
            'Todos contemplándose frente al espejo',
            'abandonando responsabilidades en tristes reflejos',
            'cabeza de familia varón machista y orgulloso fue',
            'ahora su pareja enraizó en otro lado y él también',
            'dejan prole desadaptada y carente de afectos',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap4-p4',
        slug: 'probable-equilibrio-lila',
        titulo: 'Probable equilibrio lila',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 4,
        publicado: true,
        estrofas: [
          [
            'Lila el color del gran pastel en sacra unión',
            'equilibrio de mente y cuerpo inobjetables',
            'crece y llega a florecer estabilidad conyugal',
            '¿es qué se necesita el matrimonio para ser feliz?',
            'suerte líquida movilizándose en dorada carroza',
          ],
        ],
        planchas: [],
        audios: [],
      },
    ],
  },
  {
    id: 'cap-5',
    slug: 'capitulo-5',
    volumen: 'Pentapoemario lila',
    titulo: 'Capítulo quinto',
    subtitulo: '5 poemas · capítulo V',
    descripcion: 'Cinco versos por poema. Todos los títulos empiezan por la misma letra.',
    categoria: {
      id: 'cat-pentapoemario-lila',
      slug: 'pentapoemario-lila',
      nombre: 'Pentapoemario lila',
      descripcion: 'Cinco poemas por capítulo, cinco versos por poema.',
      orden: 0,
      visible: true,
    },
    orden: 4,
    colorAcento: '#8B5CF6',
    portadaUrl: '/portadas/capitulo-5.jpg',
    anio: 2026,
    publicado: true,
    paginaBase: 65,
    poemas: [
      {
        id: 'cap5-p0',
        slug: 'paisaje-emocional-y-tardio',
        titulo: 'Paisaje emocional y tardío',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 0,
        publicado: true,
        estrofas: [
          [
            'Prodigioso sonido entre delicados pétalos',
            'cual coloridas nubes desplazándose en el día',
            'cristalino riachuelo jugueteando con guijarros',
            'algunas aves han trascendido entre trinos',
            'paisaje pintado dentro de ilusionado corazón',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap5-p1',
        slug: 'prometedores-suenos-humedos',
        titulo: 'Prometedores sueños húmedos',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 1,
        publicado: true,
        estrofas: [
          [
            'Entre contagiosos bostezos y parpados caídos',
            'lectura de novela abandonada a la mitad',
            'recetas incompletas en el chat de al lado',
            'sabanas ajadas entre leves respiraciones',
            'emergen seres alados escuchando ronquidos',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap5-p2',
        slug: 'por-un-mejor-estilo-de-vida',
        titulo: 'Por un mejor estilo de vida',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 2,
        publicado: true,
        estrofas: [
          [
            'A pasitos acompasados mira hacia la derecha',
            'rítmica y de buen ánimo gira a la izquierda',
            'aquellas bulliciosas calles llenas de acción',
            'luces nocturnas y estrellas adelante',
            'dejando todo su innombrable pasado atrás',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap5-p3',
        slug: 'presencia-de-coqueta-y-lunatica-ninfa',
        titulo: 'Presencia de coqueta y lunática ninfa',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 3,
        publicado: true,
        estrofas: [
          [
            'Envidia la sincronización de aquellos cuerpos',
            'armoniosa melodía marca cadencioso ritmo',
            'a media luz hay entrega ardorosa se aprecia',
            'en aquel viejo y grande espejo de pared',
            'rosácea luna hierve y hace tanta bulla',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap5-p4',
        slug: 'peculiar-y-majestuosa-esta-noche',
        titulo: 'Peculiar y majestuosa esta noche',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 4,
        publicado: true,
        estrofas: [
          [
            '¡Que cabello tan largo tiene esta peculiar noche!',
            'tan elegante ha vestido y perfumado a la ciudad',
            'mágica y atrevida hace gala de energía vital',
            'corona a la medianoche más nítida que nunca',
            'dándose a cíclica fuga al amanecer',
          ],
        ],
        planchas: [],
        audios: [],
      },
    ],
  },
  {
    id: 'cap-6',
    slug: 'capitulo-6',
    volumen: 'Pentapoemario lila',
    titulo: 'Capítulo sexto',
    subtitulo: '5 poemas · capítulo VI',
    descripcion: 'Cinco versos por poema. Todos los títulos empiezan por la misma letra.',
    categoria: {
      id: 'cat-pentapoemario-lila',
      slug: 'pentapoemario-lila',
      nombre: 'Pentapoemario lila',
      descripcion: 'Cinco poemas por capítulo, cinco versos por poema.',
      orden: 0,
      visible: true,
    },
    orden: 5,
    colorAcento: '#8B5CF6',
    portadaUrl: null,
    anio: 2026,
    publicado: true,
    paginaBase: 81,
    poemas: [
      {
        id: 'cap6-p0',
        slug: 'particulas-cargadas-de-deseo',
        titulo: 'Partículas cargadas de deseo',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 0,
        publicado: true,
        estrofas: [
          [
            'Ecuanimidad exige la mesa servida',
            'banquete ilícito y apetitoso demanda comensal',
            'un fragmento de restos helados, siguen en corazón',
            'impidiendo paz y consuelo ofrecidos por el sol',
            'perturbaciones se alejan con el primer abrazo',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap6-p1',
        slug: 'platonica-ensonacion',
        titulo: 'Platónica ensoñación',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 1,
        publicado: true,
        estrofas: [
          [
            'Empotrado en lo mullido para la meditación',
            'sin segundas oportunidades, se sumerge',
            'en un mundo cercano y fantástico con fruición',
            'el objeto de su deseo ardiente emerge',
            'en lo más recóndito y afiebrado de su imaginación',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap6-p2',
        slug: 'persistente-y-tozudo-a-la-deriva',
        titulo: 'Persistente y tozudo a la deriva',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 2,
        publicado: true,
        estrofas: [
          [
            'En persistente vuelo sobre canasta de frutas',
            'no se resiste al apetito desmedido y carnal',
            'encuentra complaciente flor en jardín perdido',
            'tantos aleteos esparciendo polen y ansias',
            'empuña espada y escudo en aguerrida y ruda pose',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap6-p3',
        slug: 'persecucion-no-autorizada',
        titulo: 'Persecución no autorizada',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 3,
        publicado: true,
        estrofas: [
          [
            'Viaje inesperado hacia fuente inagotable',
            'ruta de máxima y venerada sabiduría',
            'brinda experiencia y sorpresas lo vivido',
            'a lo largo de una vida de múltiples senderos',
            'sigue tu intuición y escoge tu camino',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap6-p4',
        slug: 'poderosa-melancolia',
        titulo: 'Poderosa melancolía',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 4,
        publicado: true,
        estrofas: [
          [
            'Tanto sufrimiento ahora, sin conexión aparente,',
            'con primigenia raíz, origen de mal y dolor,',
            'levitando sobre oscuro pantano, burbuja incandescente,',
            'quizás bella y efímera flor dejando su olor,',
            'lista para remontarse a la luna en su mente.',
          ],
        ],
        planchas: [],
        audios: [],
      },
    ],
  },
  {
    id: 'cap-7',
    slug: 'capitulo-7',
    volumen: 'Pentapoemario lila',
    titulo: 'Capítulo séptimo',
    subtitulo: '5 poemas · capítulo VII',
    descripcion: 'Cinco versos por poema. Todos los títulos empiezan por la misma letra.',
    categoria: {
      id: 'cat-pentapoemario-lila',
      slug: 'pentapoemario-lila',
      nombre: 'Pentapoemario lila',
      descripcion: 'Cinco poemas por capítulo, cinco versos por poema.',
      orden: 0,
      visible: true,
    },
    orden: 6,
    colorAcento: '#8B5CF6',
    portadaUrl: '/portadas/capitulo-7.jpg',
    anio: 2026,
    publicado: true,
    paginaBase: 97,
    poemas: [
      {
        id: 'cap7-p0',
        slug: 'papas-calientes-y-entretenidas',
        titulo: 'Papas calientes y entretenidas',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 0,
        publicado: true,
        estrofas: [
          [
            'En visceral y febril limbo se halla enfrascado',
            'se dispara amplio pecho creyendo que es amor',
            'persistiendo en deleite grosero y acelerado',
            'trayectoria absurda de bala penetrando flor',
            'ralentizándose inevitable hoy el tiempo brindado',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap7-p1',
        slug: 'precioso-silencio-increible-color',
        titulo: 'Precioso silencio, increíble color',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 1,
        publicado: true,
        estrofas: [
          [
            'Que imposible se presenta enmarañada vida',
            'entre los que van finiquitando toxica relación',
            'todo lo que es blanco ahora es negro en huida',
            'todo lo negro ahora es blanco de insumisión',
            'no hay medias tintas para binaria despedida',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap7-p2',
        slug: 'profundidades-oniricas-y-vitales',
        titulo: 'Profundidades oníricas y vitales',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 2,
        publicado: true,
        estrofas: [
          [
            'En oscuras profundidades de sueño vivido brilla',
            'lo terso, placentero y colorido de pétalos en acción',
            'a insectos rastreros en viscoso pantano encasilla',
            'joya perdida, valiosa y atrapada en dúctil corazón',
            'dorada época de dicha tuvo aquella floral mejilla',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap7-p3',
        slug: 'presencias-etereas-reales-e-inolvidables',
        titulo: 'Presencias etéreas, reales e inolvidables',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 3,
        publicado: true,
        estrofas: [
          [
            'Se enciende lenta y progresiva la luz en su interior',
            'no hay que mirar atrás, fueron alertas paternales',
            'tienes todo por delante susurro en oreja cómplice',
            'quien capitaneaba su destino sobre sabanas de seda',
            'sobre complaciente sofá de tres cuerpos lo meditó',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap7-p4',
        slug: 'potrillo-desbocado',
        titulo: 'Potrillo desbocado',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 4,
        publicado: true,
        estrofas: [
          [
            'Al galope y brioso irrumpe en praderas vespertinas',
            'el sol ubicado en el cenit orgulloso resplandece',
            'apariencia de níveo y sublime corcel primaveral',
            'quiere ser caballo soberbio y altivo que se admira',
            'en su mundo al combativo y febril jinete espera',
          ],
        ],
        planchas: [],
        audios: [],
      },
    ],
  },
  {
    id: 'cap-8',
    slug: 'capitulo-8',
    volumen: 'Pentapoemario lila',
    titulo: 'Capítulo octavo',
    subtitulo: '5 poemas · capítulo VIII',
    descripcion: 'Cinco versos por poema. Todos los títulos empiezan por la misma letra.',
    categoria: {
      id: 'cat-pentapoemario-lila',
      slug: 'pentapoemario-lila',
      nombre: 'Pentapoemario lila',
      descripcion: 'Cinco poemas por capítulo, cinco versos por poema.',
      orden: 0,
      visible: true,
    },
    orden: 7,
    colorAcento: '#8B5CF6',
    portadaUrl: '/portadas/capitulo-8.jpg',
    anio: 2026,
    publicado: true,
    paginaBase: 113,
    poemas: [
      {
        id: 'cap8-p0',
        slug: 'perdido-en-el-laberinto',
        titulo: 'Perdido en el laberinto',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 0,
        publicado: true,
        estrofas: [
          [
            'Es tan breve la vida para seguir resoplando',
            'cada etapa con sus propias exigencias',
            'confundido en complejo y oscuro laberinto gris',
            'corpulento y resistente cuerpo guerrero',
            'con grotesca y cornuda cabeza de toro bravío',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap8-p1',
        slug: 'pop-corn-color-lila-esperanza',
        titulo: 'Pop corn color lila esperanza',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 1,
        publicado: true,
        estrofas: [
          [
            'Millones de faustas luces danzando alrededor',
            'envolviendo apasionado y firme beso nocturno',
            'antes chispeaban en tórridas entregas carnales',
            'ahora todo es ocuparse de acelerados críos',
            'en próxima vida nacerá hermandad del paraíso',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap8-p2',
        slug: 'placeres-culposos-en-otono',
        titulo: 'Placeres culposos en otoño',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 2,
        publicado: true,
        estrofas: [
          [
            'Sobre orquídea escandalosa descansa el valle',
            'dividido sin permiso por caudaloso y tibio rio',
            'ansían estas montañas aventurarse a más',
            'donde cielos tormentosos las incitan a pecar',
            'avalancha de placer palpitando febril núcleo',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap8-p3',
        slug: 'practica-licenciosa',
        titulo: 'Práctica licenciosa',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 3,
        publicado: true,
        estrofas: [
          [
            'Trascender sigue siendo la máxima de algunos',
            'sin prestar atención a aquella ambición imperiosa',
            'evitando amanecer afuera en caros desayunos',
            'evadiendo envidiosos agresivos de forma belicosa',
            'sin sucumbir a movimientos arduos e inoportunos',
          ],
        ],
        planchas: [],
        audios: [],
      },
      {
        id: 'cap8-p4',
        slug: 'procesos-cognitivos',
        titulo: 'Procesos cognitivos',
        forma: 'pentapoema',
        dedicatoria: null,
        notaAutor: null,
        anio: 2026,
        temas: [],
        orden: 4,
        publicado: true,
        estrofas: [
          [
            'Infinitos recovecos un segundo y tibio hogar',
            'protegiendo y resguardando emergentes seres',
            'trincheras en fondo de íntimo océano sin ahogar',
            'clavadas en clara mente memorias y mensajes',
            'deslizándose y cambiando siempre de lugar',
          ],
        ],
        planchas: [],
        audios: [],
      },
    ],
  },
]
